backbone: unet
backbone_params:
  in_channels: 3
  out_channels: 3
  cnn_depths: [256, 512, 1024, 2048]
  layers_per_block: 3
  filter_size: 3
  pooling_factor: 2
  encoding_type: sinusoid
  encoding_dim: 64
  residual: True
  dropout: 0.0
  norm: True