defaults:
  - _self_
  - cifar10
  - model: unet
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

family: diffusion
task: cifar10
num_classes: 10
method: debug_diffusion_wandb
seed: 61
log_dir: logs/diffusion_debug

logger:
  filter: '.*'
  wandb: True
  wandb_entity: v1nt
  wandb_project: ml-practice

# model params
implementation: custom
model:
  max_diffusion_steps: 1000
  noise_schedule: linear
  beta_1: 1e-4
  beta_T: 0.02

# training params
batch_size: 256
val_batch_size: 1024
train_steps: 10000
print_every: 500
display_images: 16
lr: 3e-4
augment: False
data_limit: none

hydra:
  output_subdir: null
  run:
    dir: .