defaults:
  - _self_
  - placement-mini-v1
  - model: att-gnn
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

family: cond_diffusion
task: cifar10
num_classes: 10
method: debug_att_gnn
seed: 61
log_dir: logs/diffusion_debug

logger:
  filter: '.*'
  wandb: True
  wandb_entity: v1nt
  wandb_project: ml-practice

# model params
implementation: custom
model:
  max_diffusion_steps: 1000
  noise_schedule: linear
  encoding_type: sinusoid
  encoding_dim: 32
  beta_1: 1e-4
  beta_T: 0.02

# training params
batch_size: 64
val_batch_size: 64
train_steps: 300000
print_every: 1000 #1000
display_examples: 1
lr: 3e-4
augment: False
train_data_limit: none
val_data_limit: none

hydra:
  output_subdir: null
  run:
    dir: .