defaults:
  - _self_
  - placement-mini-v4
  - model: att-gnn
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

family: cond_diffusion
task: cifar10
num_classes: 10
method: debug_att_gnn
seed: 61
log_dir: logs/diffusion_debug
from_checkpoint: placement-mini-v4-L2base/latest.ckpt #none

logger:
  filter: '.*'
  wandb: True
  wandb_entity: v1nt
  wandb_project: ml-practice

# model params
implementation: custom
model:
  mask_key: is_ports
  max_diffusion_steps: 1000
  noise_schedule: linear
  encoding_type: sinusoid
  encoding_dim: 32
  beta_1: 1e-4
  beta_T: 0.02

# training params
batch_size: 64 # 64
val_batch_size: 64 # 64
train_steps: 1000000 # 5000000
print_every: 1000 #1000
eval_every: 50000
eval_samples: 32
eval_policy: open_loop
display_examples: 1
num_output_samples: 0
lr: 0 #3e-4
augment: False
train_data_limit: none
val_data_limit: none

hydra:
  output_subdir: null
  run:
    dir: .