defaults:
  - _self_
  - task@_here_: placement-mini-v5
  - model: att-gnn #graph-transformer
  - model/conv-layer@model.backbone_params: gat
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

family: cond_diffusion
task: cifar10
num_classes: 10
method: debug_att_gnn
seed: 61
log_dir: logs/diffusion_debug
from_checkpoint: none #placement-mini-v4-L2base/latest.ckpt

logger:
  filter: '.*'
  wandb: True
  wandb_entity: v1nt
  wandb_project: ml-practice

# model params
implementation: custom
model:
  mask_key: is_ports
  use_mask_as_input: True
  max_diffusion_steps: 1000
  noise_schedule: linear
  t_encoding_type: sinusoid
  t_encoding_dim: 32
  beta_1: 1e-4
  beta_T: 0.02

# training params
batch_size: 64
val_batch_size: 64
train_steps: 5000000
print_every: 5000
eval_every: 100000
eval_samples: 32
eval_policy: open_loop
display_examples: 1
num_output_samples: 0
lr: 3e-4
augment: False
train_data_limit: none
val_data_limit: none

hydra:
  output_subdir: null
  run:
    dir: .