defaults:
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

dataset_name: debug_gen
seed: 61
num_samples: 100
out_dir: data-gen/outputs
print_every: 1000

gen_params:
  max_instance: 50
  stop_density: 0.8
  aspect_ratio_dist:
    dist_type: uniform
    dist_params:
      low: 0.25
      high: 4.0
  instance_size_dist:
    dist_type: uniform
    dist_params:
      low: 0.02
      high: 0.2
  num_terminals_dist:
    dist_type: uniform
    dist_params:
      low: 1
      high: 16

logger:
  filter: '.*'
  wandb: False

hydra:
  output_subdir: null
  run:
    dir: .