defaults:
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

dataset_name: debug_att_gnn
seed: 61
num_samples: 100
out_dir: data-gen/outputs

logger:
  filter: '.*'
  wandb: False

hydra:
  output_subdir: null
  run:
    dir: .